### ISSUE TITLE
libsass version issues

### ISSUE THREAD

**Issue by ryandeussing** [budparr/webhook-starter#1]
FYI, to get this to work I needed to do this: `$ npm install --save-dev flecno/grunt-sass`

The error I was getting had to do with missing `libsass` bindings - investigating led me to unspecified `grunt-sass` incompatibility with latest version of `node-sass`.

**Comment by ryandeussing** [comment]
Turns out this solution works only with the webhook cli, and then only sometimes. Hopefully these incompatibilties will be ironed out so I can enjoy the speed of libsass soon.

**Comment by budparr** [comment]
Wonder why I didn't get the same error. I'll have a look. I know that sometimes there's a mismatch, but that should be handled with semver, I think.

**Comment by budparr** [comment]
@ryandeussing - FYI, I just loaded this up and am not having the problem. Perhaps there's some local conflict that you're having?

**Comment by ryandeussing** [comment]
Things are working for me now, after a lot of re-installing of things.
